dist: trusty
language: node_js
node_js:
- '10.18.1'
addons:
  chrome: stable
before_script:
  - npm start &
script:
  - npm run cucumber -- --require tests/cucumber.conf.js  --require step-definitions/ tests/features/ --format node_modules/cucumber-pretty
  - pkill node
